/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0Q9axNHgPPt
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Landingpage() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header
        className="bg-gradient-to-b from-gray-100 to-gray-50 dark:from-gray-800 dark:to-gray-900">
        <div
          className="container flex flex-col items-center py-4 px-4 sm:flex-row sm:justify-between sm:py-6 sm:gap-4 md:px-6">
          <Link className="flex items-center space-x-2" href="#">
            <CircleDotIcon className="w-8 h-8" />
            <span className="font-bold tracking-tighter text-gray-900 dark:text-gray-50">DocLink</span>
          </Link>
          <Link
            className="button flex items-center gap-2 text-sm rounded-full border border-gray-200 border-gray-200 bg-white px-6 py-3 shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-900 dark:hover:text-gray-50"
            href="/doctor">
            Doctor's Portal
          </Link>
          <button className="sm:hidden">
            <MenuIcon className="w-6 h-6" />
            <span className="sr-only">Toggle menu</span>
          </button>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-12 lg:py-24">
          <div
            className="container flex flex-col items-center justify-center gap-6 px-4 text-center md:gap-10 md:px-6">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-6xl">Connect with a doctor, anytime.</h1>
              <p
                className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Do not reveal any personal information!
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href="/patient">
                Access Chatroom
              </Link>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12 lg:py-24 dark:bg-gray-800">
          <div
            className="container flex flex-col items-center justify-center gap-6 px-4 text-center md:gap-10 md:px-6">
            <div className="space-y-2">
              <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl">Coming Soon: Call a Doctor</h2>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                In the future, you'll be able to connect with a doctor via video and voice call.
              </p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex-shrink-0">
        <div
          className="container flex flex-col items-center py-4 px-4 text-center gap-2 md:flex-row md:justify-between md:py-6 md:gap-4 md:px-6">
          <div
            className="flex items-center gap-2 text-xs tracking-wide sm:order-1 sm:gap-4 md:order-0 md:text-sm">
            <span className="opacity-60">© 2024 DocLink</span>
            <Link
              className="opacity-60 underline underline-offset-2 transition-colors hover:opacity-100 dark:opacity-100 dark:hover:opacity-100"
              href="#">
              Privacy
            </Link>
            <Link
              className="opacity-60 underline underline-offset-2 transition-colors hover:opacity-100 dark:opacity-100 dark:hover:opacity-100"
              href="#">
              Terms
            </Link>
          </div>
          <form className="flex items-center gap-2 text-sm sm:order-0">
            <Label className="sr-only" htmlFor="email">
              Email
            </Label>
            <Input
              className="max-w-xs border-gray-200 border-gray-200 dark:border-gray-800"
              id="number"
              placeholder="Enter phone number"
              type="number" />
            <Button type="submit">Subscribe</Button>
          </form>
          <div className="flex items-center gap-4 md:order-1">
            <Link
              className="rounded-full border border-gray-200 border-gray-200 dark:border-gray-800"
              href="#" />
          </div>
        </div>
      </footer>
    </div>)
  );
}


function CircleDotIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="1" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}
