/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DwRzHWRnWMQ
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import Link from "next/link";

export function Patientsession() {
  return (<>
    <header
      className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-800">
      <h1 className="text-xl font-semibold">DocLink</h1>
    </header>
    <div
      className="flex flex-col h-[600px] rounded-lg border border-gray-200 dark:border-gray-800">
      <div
        className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-800">
        <div className="flex items-center space-x-2">
          <div className="space-y-1.5">
            <p className="text-sm font-medium">Dr. Jamie Smith</p>
            <p className="text-sm font-medium text-gray-500 dark:text-gray-400">Neurologist</p>
          </div>
        </div>
        <Link href="/"><Button size="sm">End session</Button></Link>
      </div>
      <div className="flex-1 p-4 flex flex-col-reverse gap-4">
        <div className="flex space-x-2 items-end flex-row-reverse">
          <div className="rounded-lg bg-gray-100 flex-1 p-4 dark:bg-gray-800">
            <p className="text-sm">
              <strong>You:</strong>
              Hi, Dr. Smith. I've been having persistent headaches.
            </p>
          </div>
          <p className="text-xs text-gray-500 self-start dark:text-gray-400">10:00am</p>
        </div>
        <div className="flex space-x-2 items-end">
          <div className="rounded-lg bg-gray-100 flex-1 p-4 dark:bg-gray-800">
            <p className="text-sm">
              <strong>Dr. Smith:</strong>
              I'm sorry to hear that. Let's see how we can help.
            </p>
          </div>
          <p className="text-xs text-gray-500 self-start dark:text-gray-400">10:02am</p>
        </div>
        <div className="flex space-x-2 items-end flex-row-reverse">
          <div className="rounded-lg bg-gray-100 flex-1 p-4 dark:bg-gray-800">
            <p className="text-sm">
              <strong>You:</strong>
              Thank you, doctor. I appreciate your help.{"\n                          "}
            </p>
          </div>
          <p className="text-xs text-gray-500 self-start dark:text-gray-400">10:05am</p>
        </div>
        <div className="flex space-x-2 items-end">
          <div className="rounded-lg bg-gray-100 flex-1 p-4 dark:bg-gray-800">
            <p className="text-sm">
              <strong>Dr. Smith:</strong>
              You're welcome. Remember to stay hydrated and get enough rest.{"\n                          "}
            </p>
          </div>
          <p className="text-xs text-gray-500 self-start dark:text-gray-400">10:08am</p>
        </div>
        <div className="flex space-x-2 items-end flex-row-reverse">
          <div className="rounded-lg bg-gray-100 flex-1 p-4 dark:bg-gray-800">
            <p className="text-sm">
              <strong>You:</strong>
              I will. Thanks for the advice.{"\n                          "}
            </p>
          </div>
          <p className="text-xs text-gray-500 self-start dark:text-gray-400">10:10am</p>
        </div>
      </div>
      <div className="border-t border-gray-200 dark:border-gray-800">
        <div className="p-4 space-y-4">
          <div className="flex items-center space-x-4">
            <div className="rounded-lg bg-gray-70 flex-1 p-2 dark:bg-gray-800">
              <Input placeholder="Type a message" />
            </div>
            <Button size="icon">
              <UploadIcon className="h-4 w-4 mr-2" />
              <SendIcon className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
      
    </div>
  </>);
}


function UploadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>)
  );
}


function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="25"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}


function LinkIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>)
  );
}
