/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VABapKkTNWu
 */
import Link from "next/link"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Specialistrequests() {
  return (
    (<div className="flex flex-col min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <nav
          className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-4">
          
          <div className="flex items-center gap-4 ml-auto">
            <span className="text-gray-500 dark:text-gray-800">Dr. John Doe</span>
            <Link className="text-gray-500 dark:text-gray-400" href="#">
              Sign Out
            </Link>
          </div>
        </nav>
      </header>
      <main className="flex flex-col flex-1 gap-4 p-4 md:gap-8 md:p-10">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
            <CardTitle className="text-lg font-semibold">Pending Patients</CardTitle>
            <Link className="text-sm underline" href="#">
              View all
            </Link>
          </CardHeader>
          <CardContent className="p-0">
            <div className="divide-y">
              <div className="flex items-center justify-between p-4">
                <div className="flex items-center gap-4">
                  <UserIcon className="w-8 h-8 rounded-full" />
                  <div className="flex flex-col">
                    <h3 className="text-sm font-bold">Chat Request #123</h3>
                    <p className="text-xs text-gray-500 dark:text-gray-400">Patient is experiencing mild fever</p>
                  </div>
                </div>
                <Button size="sm">Accept</Button>
              </div>
              <div className="flex items-center justify-between p-4">
                <div className="flex items-center gap-4">
                  <UserIcon className="w-8 h-8 rounded-full" />
                  <div className="flex flex-col">
                    <h3 className="text-sm font-bold">Chat Request #124</h3>
                    <p className="text-xs text-gray-500 dark:text-gray-400">Patient is experiencing cough and cold</p>
                  </div>
                </div>
                <Button size="sm">Accept</Button>
              </div>
              <div className="flex items-center justify-between p-4">
                <div className="flex items-center gap-4">
                  <UserIcon className="w-8 h-8 rounded-full" />
                  <div className="flex flex-col">
                    <h3 className="text-sm font-bold">Chat Request #125</h3>
                    <p className="text-xs text-gray-500 dark:text-gray-400">Patient is experiencing severe headache</p>
                  </div>
                </div>
                <Button size="sm">Accept</Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>)
  );
}


function Package2Icon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
