/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sr0o6cpw4ez
 */
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuRadioItem, DropdownMenuRadioGroup, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Textarea } from "@/components/ui/textarea"
import Link from "next/link";

export function Triageportal() {
  return (
    (<div className="grid items-start gap-4 max-w-3xl w-full mx-auto px-4 pt-10">
      <div className="space-y-2">
        <div className="space-y-1">
          <h1 className="text-lg font-bold tracking-tight">#847</h1>
        </div>
        <div className="space-y-2">
          <div className="flex items-start space-x-2">
            <div className="rounded-lg bg-gray-100 w-3/4 p-4 text-sm dark:bg-gray-800">
              Hi, I'm Dr. Triage. How can I help you today?
            </div>
            <div className="w-1/4 text-right text-sm text-gray-500 dark:text-gray-400">10:00 AM</div>
          </div>
          <div className="flex items-start space-x-2">
            <div className="rounded-lg bg-gray-100 w-3/4 p-4 text-sm dark:bg-gray-800">
              I'm feeling a sharp pain in my chest and I'm short of breath.
            </div>
            <div className="w-1/4 text-right text-sm text-gray-500 dark:text-gray-400">10:01 AM</div>
          </div>
        </div>
        <div className="space-y-2">
          <div className="flex items-start space-x-2">
            <div className="rounded-lg bg-gray-100 w-3/4 p-4 text-sm dark:bg-gray-800">
              I'm feeling a sharp pain in my chest and I'm short of breath.
            </div>
            <div className="w-1/4 text-right text-sm text-gray-500 dark:text-gray-400">10:01 AM</div>
          </div>
          <div className="flex items-start space-x-2">
            <div className="rounded-lg bg-gray-100 w-3/4 p-4 text-sm dark:bg-gray-800">
              Thank you for letting me know. I'll ask you a few questions to better understand your symptoms.
            </div>
            <div className="w-1/4 text-right text-sm text-gray-500 dark:text-gray-400">10:02 AM</div>
          </div>
        </div>
        <div className="grid gap-2">
          <div className="rounded-lg border">
            <div className="grid items-center grid-cols-2 p-2">
              <div className="text-sm text-gray-500 dark:text-gray-400">Assign to department</div>
              <div className="flex items-center space-x-2 text-right">
                <Label className="sr-only" htmlFor="department">
                  Department
                </Label>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button className="w-[200px]" variant="outline">
                      Cardiology
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="start" className="w-[200px]">
                    <DropdownMenuRadioGroup defaultValue="cardioogy">
                      <DropdownMenuRadioItem value="cardiology">Cardiology</DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="pediatrics">Pediatrics</DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="orthopedics">Orthopedics</DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="neurology">Neurology</DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="oncology">Oncology</DropdownMenuRadioItem>
                    </DropdownMenuRadioGroup>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>
          </div>
          <div className="rounded-lg border">
            <div className="grid items-center grid-cols-2 p-2">
              <div className="text-sm text-gray-500 dark:text-gray-400">Case severity</div>
              <div className="flex items-center space-x-2 text-right">
                <Label className="sr-only" htmlFor="severity">
                  Severity
                </Label>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button className="w-[200px]" variant="outline">
                      Medium
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="start" className="w-[200px]">
                    <DropdownMenuRadioGroup defaultValue="medium">
                      <DropdownMenuRadioItem value="extreme">Extreme</DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="medium">Medium</DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="low">Low</DropdownMenuRadioItem>
                    </DropdownMenuRadioGroup>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>
          </div>
        </div>
        <form className="grid gap-2">
          <Label className="sr-only" htmlFor="message">
            Message
          </Label>
          <Textarea className="min-h-[100px]" id="message" placeholder="Type your message..." />
          <Link href="/doctor/specialist/"><Button className="w-full" type="submit">
            Send
          </Button></Link>
        </form>
      </div>
    </div>)
  );
}
